---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/xiaods/concourse-tutorial.git
- name: resource-gist
  type: git
  source:
    uri: https://gist.github.com/b8f3b74b751c29a75bd1.git
    private_key:
    branch: master

jobs:
- name: job-bump-date
  serial: true
  plan:
  - get: resource-tutorial
  - get: resource-gist
  - task: bump-timestamp-file
    file: resource-tutorial/12_publishing_outputs/bump-timestamp-file.yml
  - put: resource-gist
    params: {repository: updated-gist}
